Relewise/relewise-demos-shop-vue

package-lock.json, package.json, src/components/SearchOverlay.vue
https://trello.com/c/MJ34FYJd/4394-use-new-js-sdk-version-1200-in-demo-store-to-support-cancellation
=> Feat: update to js sdk 1.20.0

src/views/ProductDetails.vue
https://trello.com/c/AmcacIl2/7382-demo-shop-seems-to-deliver-wrong-result-in-recommendation-on-first-loadsometimes
=> Fix: Recommendations were not updated after selecting newly searched product

package-lock.json, package.json, src/components/Popover.vue, src/components/ProductTile.vue, src/main.ts
Jeg tager gerne i mod forbedringer til hvad der skal stå! 💗
https://trello.com/c/khcqWf5K/7854-demo-shop-add-a-small-hint-why-am-i-seeing-this-to-the-sponsored-label-in-retail-media-product-listings
=> Feat: Explain Sponsored

src/stores/context.store.ts
https://trello.com/c/m5IOafa9/8001-demoshop-cannot-load-old-stored-dataset-languages-and-currencies?filter=member:simonwalenkamphansen
=> Fix: add missing arrays to stored context

src/layout/Header.vue
https://trello.com/c/WhIzHP1j/7992-demoshop-weird-scrolling-behavior-on-category-pages?[filter=member:simonwalenkamphansen](https://trello.com/c/WhIzHP1j/7992-demoshop-weird-scrolling-behavior-on-category-pages?filter=member:simonwalenkamphansen)
=> Fix: Weird scrolling behavior

src/layout/Header.vue
https://trello.com/c/yHB19kvM/7990-demoshop-visual-bug-on-safari-when-opening-the-categories-in-the-header
=> Fix: header jumps to the right when categories are hovered

src/App.vue, src/components/Breadcrumb.vue, src/components/SearchOverlay.vue, src/helpers/categoryHelper.ts, src/views/Category.vue, src/views/HomeView.vue, src/views/ProductDetails.vue, src/views/Settings.vue
https://trello.com/c/SUhbwPpp/8087-demoshop-when-going-to-various-category-pages-we-would-like-the-breadcrum-for-the-category-to-be-rendered?filter=member:simonwalenkamphansen
=> Feat: Breadcrumb

src/components/DatasetSettings.vue, src/components/ProductTile.vue, src/components/SearchOverlay.vue, src/components/WebComponentProductTemplate.ts, src/stores/context.store.ts, src/stores/globalProductFilters.ts, src/views/Cart.vue, src/views/Category.vue, src/views/HomeView.vue, src/views/ProductDetails.vue
=> feat: Add new UI features

src/App.vue, src/components/OnSaleSlider.vue, src/styling/index.scss, src/views/Cart.vue, src/views/ProductDetails.vue
https://trello.com/c/3e1nIENe
https://trello.com/c/WBCkaflR
=> feat: fix animations

src/components/Facets.vue, src/components/SearchOverlay.vue, src/views/Category.vue, src/views/HomeView.vue
https://trello.com/c/fiHBNyXV/8698-demo-shop-make-brand-search-look-like-a-brand-page
=> feat: make brand search look like a brand page

src/App.vue, src/components/HeroBanner.vue, src/views/HomeView.vue
=> feat: disable page animation and adjust hero banner

src/components/DatasetSettings.vue
https://trello.com/c/phN1HyCK/8745-demo-shop-share-link-should-also-include-features-used-on-dataset
=> Feat: Share features

src/App.vue
https://trello.com/c/3tF7yud1/8859-demo-shop-look-for-a-datasetid-query-param
=> Feat: switch to dataset from query

src/components/SearchOverlay.vue, src/views/Category.vue
https://trello.com/c/frtKhlRW/8823-demo-shop-navigation
=> Fix: navigation history on search and category pages

src/views/Category.vue
https://trello.com/c/UVa4Nm5g/9009-demo-shop-retail-media-right-placement-ads-are-not-rendered?filter=member:simonwalenkamphansen
=> Fix: Right products were always rendered outside the page

src/components/ContextSwitcher.vue
=> Feat: Keep the context switcher open when changing values

src/components/HeroBanner.vue, src/components/PopularCategories.vue, src/views/HomeView.vue
=> Feat: Home page categories redesign

src/components/OnSaleSlider.vue
=> Fix: only show on sale recommendation haeder when results found

src/components/DatasetSettings.vue, src/views/ProductDetails.vue
=> feat: Show StockLevels if present and handle PascalCase Description

src/components/ContentTile.vue, src/components/Facets.vue, src/components/Image.vue, src/components/ProductTile.vue, src/components/SearchOverlay.vue, src/router/index.ts, src/services/tracking.service.ts, src/stores/context.store.ts, src/styling/index.scss, src/views/Cart.vue, src/views/ContentDetails.vue, src/views/ProductDetails.vue
=> Feature: content

src/components/DatasetSettings.vue, src/components/SearchOverlay.vue, src/helpers/relevanceModifierHelper.ts, src/views/Category.vue
=> Feature: Add relevance modifiers based on utm query params

src/components/OnSaleSlider.vue, src/stores/context.store.ts, src/views/Cart.vue, src/views/ContentDetails.vue, src/views/HomeView.vue, src/views/ProductDetails.vue
=> Feature: lower the amount of products recommended

src/components/DatasetSettings.vue, src/components/SearchOverlay.vue, src/stores/context.store.ts, src/stores/globalProductFilters.ts, src/views/Category.vue, src/views/ProductDetails.vue
=> Feature: user classification based filters

src/components/OnSaleSlider.vue, src/components/ProductTile.vue, src/components/WebComponentProductTemplate.ts, src/stores/globalProductFilters.ts, src/views/ProductDetails.vue
=> Fix: SoldOut and OnSale are multilingual in demo data

src/views/ContentDetails.vue
=> Fix: Hide product slider on content when no products

package-lock.json, package.json, src/components/DatasetSettings.vue, src/components/ProductTile.vue, src/stores/context.store.ts
=> feat: Add feature toggle to show product relevance score

src/components/CategoryFacet.vue
=> Fix: Category facet hits styling

src/components/ContentTile.vue, src/components/DatasetSettings.vue, src/components/ProductSearchOverlayResult.vue, src/components/ProductTile.vue, src/components/SearchOverlay.vue, src/helpers/highligther.ts, src/stores/context.store.ts
=> Feature: Add a toggle to highlight matched words in product search
